---
# Make sure to ask for password <--ask-pass>
# And point to the public key <--extra-vars "pubkey=~/.ssh/id_rsa.pub"

- hosts: all
  become: True
  vars:
    sshpath: "/root/.ssh"
  gather_facts: False
  tasks:
  - name: create directory to deploy ssh keys
    file:
      path: "{{ sshpath }}"
      state: directory

  - name: create empty file
    file:
      path: "{{sshpath}}/authorized_keys"
      state: touch

  - name: get and put the key on the right place
    lineinfile:
      path: "{{sshpath}}/authorized_keys"
      line: "{{ pubkey }}"
