---
- hosts: all
  become: True
  tasks:
  - name: Check FileSystem
    shell: df -h
    register: fs_space
  - debug: msg="{{ fs_space.stdout }}"
  - name: Kernel Check
    shell: uname -r
    register: kernel
  - debug: msg="{{ kernel.stdout }}"
  
